name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          # cache: gradle

      - name: Check Gradle version
        run: |
          chmod +x gradlew
          ./gradlew --version

      - name: Force Gradle wrapper download
        run: |
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 8.12.1

      - name: Check Gradle version 2
        run: |
          chmod +x gradlew
          ./gradlew --version

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test -Dspring.profiles.active=integration -Dspring.cloud.config.enabled=false
          echo "=== Searching for JARs recursively ==="
          find ${{ github.workspace }} -type f -name "*.jar"

      - name: Debug Gradle build
        run: |
          echo "=== Gradle tasks run ==="
          ./gradlew tasks --all | grep build
          echo "=== Check build outputs ==="
          find build -maxdepth 3 -type f || true


      - name: List build artifacts
        run: |
          echo "Root build/libs:"
          ls -l ${{ github.workspace }}/build/libs || true

      - name: Run grype scanner
        run: |
          touch ${{ github.workspace }}/scan-results.sarif
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b . v0.74.4
          ./grype dir:${{ github.workspace }}/build/libs -o sarif > ${{ github.workspace }}/scan-results.sarif || true

      - name: Debug SARIF file
        if: always()
        run: |
          echo "==== build/libs content ===="
          ls -l ${{ github.workspace }}/build/libs || true
          echo "==== SARIF file ===="
          ls -l ${{ github.workspace }}/scan-results.sarif || true
          echo "==== SARIF preview ===="
          head -n 50 ${{ github.workspace }}/scan-results.sarif || true

      - name: Upload vulnerability report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/scan-results.sarif

      - name: Upload JAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: catalog-service-jar
          path: build/libs/*.jar
